version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aether-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aether
    ports:
      - '5432:5432'
    volumes:
      - aether-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: aether-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - aether-redis-data:/data

volumes:
  aether-db-data:
  aether-redis-data:
